package com.example.aashna.asd;

import android.Manifest;
import android.app.AlertDialog;
import android.content.Context;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.os.AsyncTask;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.AppCompatActivity;
import android.telephony.SmsManager;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.Toast;

import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.NameValuePair;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.HttpClient;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.impl.client.DefaultHttpClient;
import org.apache.http.message.BasicNameValuePair;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Main2Activity extends AppCompatActivity {

    EditText editRollno, editName, editMarks, editText, editText2, editText3;
    SQLiteDatabase db1;
    String text11;
    int RPS;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);
        editRollno = (EditText) findViewById(R.id.editRollno);
        editName = (EditText) findViewById(R.id.editName);
        editText = (EditText) findViewById(R.id.editText);
        editMarks = (EditText) findViewById(R.id.editMarks);

        if(ContextCompat.checkSelfPermission(Main2Activity.this, Manifest.permission.SEND_SMS)!= PackageManager.PERMISSION_GRANTED)
        {
            ActivityCompat.requestPermissions(Main2Activity.this, new String[]{Manifest.permission.SEND_SMS, Manifest.permission.INTERNET}, RPS);
        }
        editText2 = (EditText) findViewById(R.id.editText2);
        editText3= (EditText) findViewById(R.id.editText3);
        db1=openOrCreateDatabase("empInfo", Context.MODE_PRIVATE, null);
        db1.execSQL("CREATE TABLE IF NOT EXISTS emp(empName VARCHAR,empNo VARCHAR);");
        db1.execSQL("INSERT INTO emp VALUES ('A C Mohanty (FINANCE)','9650997728');");
        db1.execSQL("INSERT INTO emp VALUES ('A K Tripathi (OPERATION)','9650994144');");
        db1.execSQL("INSERT INTO emp VALUES ('Abha Mathur (O&G)','8527597184');");
        db1.execSQL("INSERT INTO emp VALUES ('ABHAY SINGH (FUEL MANAGMENT)','9650999736');");
        db1.execSQL("INSERT INTO emp VALUES ('ABHIRAM PANDEY AVINASHI (OPERATION)','9650994419');");
        db1.execSQL("INSERT INTO emp VALUES ('ACHINT MITTAL (MECH MAINT- TURBINE)','9650994095');");
        db1.execSQL("INSERT INTO emp VALUES ('AJAY BARELIYA (PLANT CIVIL MAINT.)','9650999435');");
        db1.execSQL("INSERT INTO emp VALUES ('AJEET SINGH VAGLE (OPERATION)','9650994420');");
        db1.execSQL("INSERT INTO emp VALUES ('AKHILESH KUMAR (C&M)','8800597577');");
        db1.execSQL("INSERT INTO emp VALUES ('ALOK RAIZADA (ASH MANAGEMENT)','9650993862');");
        db1.execSQL("INSERT INTO emp VALUES ('AMANPREET KAUR (C&M)','9650992502');");
        db1.execSQL("INSERT INTO emp VALUES ('AMANPREET RATTAN (OPERATION)',',9530603356');");
        db1.execSQL("INSERT INTO emp VALUES ('AMIT KAUSHIK (OPERATION)','9650994655');");
        db1.execSQL("INSERT INTO emp VALUES ('AMIT KUMAR GOSWAMI (OPERATION)','9650993656');");
        db1.execSQL("INSERT INTO emp VALUES ('AMIT THAKUR (MAINT. PLNG.)','9650993809');");
        db1.execSQL("INSERT INTO emp VALUES ('ANAND JI AGARWAL (IT)','9415501022');");
        db1.execSQL("INSERT INTO emp VALUES ('ANAND KISHORE MISHRA (FLD. ENGG.)','9650994280');");
        db1.execSQL("INSERT INTO emp VALUES ('ANAND PRAKASH SRIVASTAVA (MEDICAL)','');");
        db1.execSQL("INSERT INTO emp VALUES ('ANAND PURI (FUEL HAND.)','9650999732');");
        db1.execSQL("INSERT INTO emp VALUES ('ANIL KUMAR (CHEM-EXPRESS LAB)','');");
        db1.execSQL("INSERT INTO emp VALUES ('ANIL KUMAR GUPTA (FUEL HAND.-OPN)','9650994153');");
        db1.execSQL("INSERT INTO emp VALUES ('ANIL KUMAR KALRA (OPERATION)','9650994127');");
        db1.execSQL("INSERT INTO emp VALUES ('ANIL KUMAR SEHLOTH (MEDICAL)','9650993688');");
        db1.execSQL("INSERT INTO emp VALUES ('ANIL KUMAR SHARMA (FINANCE)','9650993561');");
        db1.execSQL("INSERT INTO emp VALUES ('ANIL KUMAR SINGH (FUEL MANAGMENT)','9650999837');");
        db1.execSQL("INSERT INTO emp VALUES ('ANISH KUMAR (MECH MAINT-OFF SITE)','9650996276');");
        db1.execSQL("INSERT INTO emp VALUES ('ANITA GUPTA (FINANCE)','9650991764');");
        db1.execSQL("INSERT INTO emp VALUES ('ANKUR KUMAR (OPERATION)','9650999525');");
        db1.execSQL("INSERT INTO emp VALUES ('ANSHUL GOEL (OPERATION)','9650993720');");
        db1.execSQL("INSERT INTO emp VALUES ('ANUJA SETH (ELECT MAINT)','8527597156');");
        db1.execSQL("INSERT INTO emp VALUES ('ANURAG TIWARI (MECH MAINT-BOILER)','9650993727');");
        db1.execSQL("INSERT INTO emp VALUES ('ARUN KUMAR MAHAJAN (OPERATION)','9650993716');");
        db1.execSQL("INSERT INTO emp VALUES ('ARUN KUMAR PAL (MAINT. PLNG.)','9650992147');");
        db1.execSQL("INSERT INTO emp VALUES ('ASHISH KUMAR (MECH MAINT. BOILER)','9650999197');");
        db1.execSQL("INSERT INTO emp VALUES ('ASHISH KUMAR AGARWAL (OPERATION)','9650994218');");
        db1.execSQL("INSERT INTO emp VALUES ('ASHISH KUMAR BANSAL (ELECT MAINT.)','9650994076');");
        db1.execSQL("INSERT INTO emp VALUES ('ASHOK KUMAR (EEMG)','9650994056');");
        db1.execSQL("INSERT INTO emp VALUES ('ASHOK KUMAR (FUEL HAND.-OPN)','9650994150');");
        db1.execSQL("INSERT INTO emp VALUES ('ASHOK KUMAR DABAS (ELECT MAINT)','9650994290');");
        db1.execSQL("INSERT INTO emp VALUES ('ASHOK KUMAR KAPOOR (C&I MAINT.)','9650994176');");
        db1.execSQL("INSERT INTO emp VALUES ('ASHOK KUMAR PAL (PLANT CIVIL MAINT. )','9650999442');");
        db1.execSQL("INSERT INTO emp VALUES ('ASHOK KUMAR TRIPATHI (FUEL MANAGMENT)','9650996871');");
        db1.execSQL("INSERT INTO emp VALUES ('ASHOK KUMAR VERMA (OPERATION)','9650994090');");
        db1.execSQL("INSERT INTO emp VALUES ('ASHRAF ALI (MECH MAINT-BOILER)','9650994723');");
        db1.execSQL("INSERT INTO emp VALUES ('ASIT KUMAR DEY (SAFETY)','9650995444');");
        db1.execSQL("INSERT INTO emp VALUES ('B K BHARALI (MEDICAL)','7065027010');");
        db1.execSQL("INSERT INTO emp VALUES ('B P KALRA (BUSINESS EXCELLENCE)','9650999255');");
        db1.execSQL("INSERT INTO emp VALUES ('. MAMTA RANI','9650994228');");
        db1.execSQL("INSERT INTO emp VALUES ('. Munna','7042497206');");
        db1.execSQL("INSERT INTO emp VALUES ('BABITA SHEKHAWAT (HR-EDC)','9650990952');");
        db1.execSQL("INSERT INTO emp VALUES ('BABU LAL (FUEL HAND.-OPN)','7042497227');");
        db1.execSQL("INSERT INTO emp VALUES ('BALI RAM (C&M)','9650996870');");
        db1.execSQL("INSERT INTO emp VALUES ('BANWARI LAL (FUEL HAND.-OPN )','9650999247');");
        db1.execSQL("INSERT INTO emp VALUES ('BASANT SINGH (OPN(MAIN PLANT))','9650993608');");
        db1.execSQL("INSERT INTO emp VALUES ('BHAGWAT (MAINT. PLNG.)','9650999741');");
        db1.execSQL("INSERT INTO emp VALUES ('BHARAT LAL SHARMA (FINANCE)','9650999128');");
        db1.execSQL("INSERT INTO emp VALUES ('BHIM SAIN (CHEM-WTP)','9650993678');");
        db1.execSQL("INSERT INTO emp VALUES ('BHUPENDER KUMAR VERMA (FINANCE)','9650994970');");
        db1.execSQL("INSERT INTO emp VALUES ('BHUPINDER SINGH (C&I MAINT)','9650994198');");
        db1.execSQL("INSERT INTO emp VALUES ('BIDESHI (CHEM-EXPRESS LAB)','9717881378');");
        db1.execSQL("INSERT INTO emp VALUES ('BIJALI PRASAD (MECH MAINT-OFF SITE)','-');");
        db1.execSQL("INSERT INTO emp VALUES ('BINOD KUMAR MISHRA (MEDICAL)','9650993604');");
        db1.execSQL("INSERT INTO emp VALUES ('BISHAN SINGH JAGGI (ASH MNGMT.)','9650997839');");
        db1.execSQL("INSERT INTO emp VALUES ('BISHAN SWAROOP (MEDICAL)','9650993614');");
        db1.execSQL("INSERT INTO emp VALUES ('BRAHM PRAKASH (ELECT MAINT.)','7042497275');");
        db1.execSQL("INSERT INTO emp VALUES ('BRAHM SHANKER (MECH MAINT-BOILER)','9650999528');");
        db1.execSQL("INSERT INTO emp VALUES ('BARHM PAL SINGH (OPERATION)','7065027072');");
        db1.execSQL("INSERT INTO emp VALUES ('BRIJ MOHAN SINGH RAWAT (BUSINESS EXCELLENCE)','9650999042');");
        db1.execSQL("INSERT INTO emp VALUES ('BRIKESH KUMAR DUBEY (OPERATION)','9650996583');");
        db1.execSQL("INSERT INTO emp VALUES ('BUDH RAM (FUEL HAND.-OPN)','9650994047');");
        db1.execSQL("INSERT INTO emp VALUES ('CHANDAN CHAKRABORTY (HEAD OF PROJECT)','9650994355');");
        db1.execSQL("INSERT INTO emp VALUES ('CHETAN ANAND SINGH (C&I MAINT.)','9650999229');");
        db1.execSQL("INSERT INTO emp VALUES ('CHETRAM MEENA (OPERATION)','9650999547');");
        db1.execSQL("INSERT INTO emp VALUES ('DALEEP SINGH ARORA (BUSINESS EXCELLENCE)','9650994010');");
        db1.execSQL("INSERT INTO emp VALUES ('DAVID SUNIL MASIH (MEDICAL)','9650994890');");
        db1.execSQL("INSERT INTO emp VALUES ('DEBI PRASAD DUTTA (ELECT MAINT)','9650996809');");
        db1.execSQL("INSERT INTO emp VALUES ('DEEPAK KUMAR DAHIYA (OPERATION)','9650994084');");
        db1.execSQL("INSERT INTO emp VALUES ('DEEPAK KUMAR RAI (MECH MAINT-BOILER)','9650999554');");
        db1.execSQL("INSERT INTO emp VALUES ('DEEPAK SAHAI (MECH MAINT-BOILER)','9650995037');");
        db1.execSQL("INSERT INTO emp VALUES ('DEEPCHAND MEENA (OPERATION)','9650993698');");
        db1.execSQL("INSERT INTO emp VALUES ('DEEPSHIKHA JOSHI (C&I MAINT.)','9650995336');");
        db1.execSQL("INSERT INTO emp VALUES ('DEV RAJ (ELECT MAINT)','9650998181');");
        db1.execSQL("INSERT INTO emp VALUES ('DEVENDER KUMAR (OPERATION)','9650993951');");
        db1.execSQL("INSERT INTO emp VALUES ('DEVINDER KUMAR (P&S)','9650995306');");
        db1.execSQL("INSERT INTO emp VALUES ('DHAN SINGH RAWAT (OPERATION)','9650993772');");
        db1.execSQL("INSERT INTO emp VALUES ('DHARAM VIR YADAV (HR)','9650993890');");
        db1.execSQL("INSERT INTO emp VALUES ('DHARAMVIR SINGH MATHUR (FUEL HAND.-OPN)','9650994243');");
        db1.execSQL("INSERT INTO emp VALUES ('DHARMENDER KUMAR (OPERATION)','9650997617');");
        db1.execSQL("INSERT INTO emp VALUES ('DHIRENDRA KUMAR PATHAK (PAEDIATRICIAN)','9650999832');");
        db1.execSQL("INSERT INTO emp VALUES ('DINA NATH (FUEL HAND.-OPN)','9650999216');");
        db1.execSQL("INSERT INTO emp VALUES ('DINESH CHANDRA SINGH (CHEMISTRY)','9650999241');");
        db1.execSQL("INSERT INTO emp VALUES ('DINESH KUMAR SHARMA (FUEL HAND.-OPN)','9650998843');");
        db1.execSQL("INSERT INTO emp VALUES ('DINESH SINGH (FUEL HAND.-OPN)','9650993902');");
        db1.execSQL("INSERT INTO emp VALUES ('DULI CHAND (OPERATION)','-');");
        db1.execSQL("INSERT INTO emp VALUES ('DUSHYANT KUMAR KAUSHIK (OPERATION)ELMA LAL (MEDICAL)','9650993689');");
        db1.execSQL("INSERT INTO emp VALUES ('ELMA LAL (MEDICAL)','-');");
        db1.execSQL("INSERT INTO emp VALUES ('G MOHAN KUMARAN (OPERATION)','9650993673');");
        db1.execSQL("INSERT INTO emp VALUES ('GAGANDEEP SINGH (FINANCE)','9650999182');");
        db1.execSQL("INSERT INTO emp VALUES ('GANGA RAM YADAV (FUEL MANAGMENT)','9650994156');");
        db1.execSQL("INSERT INTO emp VALUES ('GAURAV AGRAWAL (C & I MAINT.)','7042244889');");
        db1.execSQL("INSERT INTO emp VALUES ('GAURAV GOYAL (MECH MAINT- OFF SITE)','9650994208');");
        db1.execSQL("INSERT INTO emp VALUES ('GEETA GAUR (HR-ER)','9650993526');");
        db1.execSQL("INSERT INTO emp VALUES ('GEETIKA MOHAN GUPTA (FINANCE)','9650999183');");
        db1.execSQL("INSERT INTO emp VALUES ('GHANSHYAM SARAN KHANNA (C&M STORES)','9650994018');");
        db1.execSQL("INSERT INTO emp VALUES ('GOPI NATH BHERA (C&M)','9818072208');");
        db1.execSQL("INSERT INTO emp VALUES ('GULBIR SINGH CHAUHAN (OPERATION)','9650992681,9416212383');");
        db1.execSQL("INSERT INTO emp VALUES ('GURPREET SINGH HEER (MECH MAINT-TURBINE)','9650994919');");
        db1.execSQL("INSERT INTO emp VALUES ('GURUCHARAN SINGH (PLANT CIVIL MAINT)','9650994263');");
        db1.execSQL("INSERT INTO emp VALUES ('GURUDAS MISHRA (OPERATION)','9650993748');");
        db1.execSQL("INSERT INTO emp VALUES ('GYARSI LAL VERMA (OPERATION)','7042497257');");
        db1.execSQL("INSERT INTO emp VALUES ('H.C.AHUJA (C&I MAINT-BOILER)','9650994244');");
        db1.execSQL("INSERT INTO emp VALUES ('HAKIM SINGH RANA (HR-E S)','9650996455');");
        db1.execSQL("INSERT INTO emp VALUES ('HARDAN SINGH (FUEL HAND.-OPN)','9650999903');");
        db1.execSQL("INSERT INTO emp VALUES ('HARE RAM (FUEL HAND.-MECH MAIN)','9650993848');");
        db1.execSQL("INSERT INTO emp VALUES ('HARI OM (OPERATION)','7042497278');");
        db1.execSQL("INSERT INTO emp VALUES ('HARI SINGH (OPERATION)','');");
        db1.execSQL("INSERT INTO emp VALUES ('HARINAM DAS GUPTA (HR-HINDI)','9810897818');");
        db1.execSQL("INSERT INTO emp VALUES ('HARISH CHANDRA BHATT (CHEM-EXPRESS LAB)','9650993796');");
        db1.execSQL("INSERT INTO emp VALUES ('HARISH CHANDRA VERMA (MECH MAINT-TURBINE)','9650993831');");
        db1.execSQL("INSERT INTO emp VALUES ('HARISH KUMAR BAJAJ (HOP SECT)','9650993636');");
        db1.execSQL("INSERT INTO emp VALUES ('HARISH KUMAR SIKRI (CHEMISTRY)','9650993751');");
        db1.execSQL("INSERT INTO emp VALUES ('HARJEET KAUR (DENTISTRY)','9650993612');");
        db1.execSQL("INSERT INTO emp VALUES ('HARSH GAUR (C&I MAINT)','9650999847');");
        db1.execSQL("INSERT INTO emp VALUES ('HARSH KUMAR SRIVASTAVA (MECH MAINT-OFF SITE)','8130893130');");
        db1.execSQL("INSERT INTO emp VALUES ('HARSOHENA MULTANI (EEMG)','9650994416');");
        db1.execSQL("INSERT INTO emp VALUES ('HARVINDER SINGH (C&M-CONTRACTS)','8527317890');");
        db1.execSQL("INSERT INTO emp VALUES ('HAWALDAR RAM (MEDICAL)','');");
        db1.execSQL("INSERT INTO emp VALUES ('HIMAT SINGH (C&I MAINT-TURBINE)','7042497296');");
        db1.execSQL("INSERT INTO emp VALUES ('HIRA LAL (OPERATION)','9650993693');");
        db1.execSQL("INSERT INTO emp VALUES ('INDER KUMAR GANOTRA (HR)','9650991228');");
        db1.execSQL("INSERT INTO emp VALUES ('ISHRAT PARVEEN (MEDICAL)','9650993626');");
        db1.execSQL("INSERT INTO emp VALUES ('ISHWER SINGH SAINI (FINANCE)','9650993243');");
        db1.execSQL("INSERT INTO emp VALUES ('J.D.NAVEEN KUMAR (FUEL HAND.- OPN)','9650999080');");
        db1.execSQL("INSERT INTO emp VALUES ('JAGDISH. (FUEL HAND.- OPN)','9650993900');");
        db1.execSQL("INSERT INTO emp VALUES ('JAGDISH KUMAR (FUEL HAND.- OPN)','9650994027');");
        db1.execSQL("INSERT INTO emp VALUES ('JAGDISH KUMAR MAHAUR (FUEL HAND.- OPN)','9650994185');");
        db1.execSQL("INSERT INTO emp VALUES ('JAI BHAN SINGH (IT)','9650993632');");
        db1.execSQL("INSERT INTO emp VALUES ('JAI LAL (FUEL MANAGEMENT)','9650993661');");
        db1.execSQL("INSERT INTO emp VALUES ('JAI PRAKASH (FUEL HAND.- OPN)','9650994137');");
        db1.execSQL("INSERT INTO emp VALUES ('JASWANT SINGH (FUEL HAND.- OPN)','9650994258');");
        db1.execSQL("INSERT INTO emp VALUES ('JAWAHAR SINGH (OPERATION)','9650993578');");
        db1.execSQL("INSERT INTO emp VALUES ('JHARKHANDEY SINGH (FUEL HAND.- OPN)','9650999186');");
        db1.execSQL("INSERT INTO emp VALUES ('JHINNU PRASAD (FUEL HAND.- OPN)','9560305091');");
        db1.execSQL("INSERT INTO emp VALUES ('JODHA SINGH (FUEL HAND.- OPN)','9650999015');");
        db1.execSQL("INSERT INTO emp VALUES ('K MANDAL (EEMG)','9650993818');");
        db1.execSQL("INSERT INTO emp VALUES ('K.VIJAYA MOHANAN THAMBI (MEDICAL)','9650993963');");
        db1.execSQL("INSERT INTO emp VALUES ('KALPANA BASU (IT)','9650993635');");
        db1.execSQL("INSERT INTO emp VALUES ('KALYAN MONDAL (C & I MAINT)','9650999343');");
        db1.execSQL("INSERT INTO emp VALUES ('KAMALESH PRASAD (MECH MAINT- OFF SITE)','9650999276');");
        db1.execSQL("INSERT INTO emp VALUES ('KAMLA PRASAD (ELECT MAINT)','');");
        db1.execSQL("INSERT INTO emp VALUES ('KANCHAN PRIYA (C & I MAINT)','9650999320');");
        db1.execSQL("INSERT INTO emp VALUES ('KAPIL. (PLANT CIVIL MAINT)','9650994428');");
        db1.execSQL("INSERT INTO emp VALUES ('KAPIL DHVAJ TYAGI (OPERATION)','9650994108');");
        db1.execSQL("INSERT INTO emp VALUES ('KARAM VIR SINGH (FUEL HAND.- OPN)','9650993837');");
        db1.execSQL("INSERT INTO emp VALUES ('KARAMJIT SINGH (FUEL HAND.- OPN)','9650994716');");
        db1.execSQL("INSERT INTO emp VALUES ('KARAN SINGH (FUEL HAND.- OPN)','');");
        db1.execSQL("INSERT INTO emp VALUES ('KARTAVYA AGARWAL (OPERATION)','9650999189');");
        db1.execSQL("INSERT INTO emp VALUES ('KAVITA ROHILLA JAIN (HR-EB)','9650999307');");
        db1.execSQL("INSERT INTO emp VALUES ('KESARAPU SATYANARAYAN (MAINT.PLNG.)','9650993810');");
        db1.execSQL("INSERT INTO emp VALUES ('KESHAV PRASAD MEENA (PLANT CIVIL MAINT.)','9650999811');");
        db1.execSQL("INSERT INTO emp VALUES ('KHEVENDER KUMAR (C & I MAINT-BOILER)','9650994225');");
        db1.execSQL("INSERT INTO emp VALUES ('KHUB RAM (ELECT MAINT)','9650991601');");
        db1.execSQL("INSERT INTO emp VALUES ('KHUSHNANDAN PRASAD SINGH (OPERATION)','9650994046');");
        db1.execSQL("INSERT INTO emp VALUES ('KIRAN PATHARIYA (MEDICAL)','7042497203');");
        db1.execSQL("INSERT INTO emp VALUES ('KRISHAN CHANDER. (FUEL HAND.- OPN)','9650994026');");
        db1.execSQL("INSERT INTO emp VALUES ('KRISHAN CHANDRA SHARMA (OPERATION)','9650994143');");
        db1.execSQL("INSERT INTO emp VALUES ('KRISHAN DEV (OPERATION)','9650993655');");
        db1.execSQL("INSERT INTO emp VALUES ('KUMAR SAURABH(OPERATION)','9650999492');");
        db1.execSQL("INSERT INTO emp VALUES ('KUSH KUMAR SRIVASTWA (OPERATION)','9650993737');");
        db1.execSQL("INSERT INTO emp VALUES ('LAKHPAT SINGH (OPERATION)','9650993657');");
        db1.execSQL("INSERT INTO emp VALUES ('LALIT SONI (UEL MANAGEMENT)','9650991412');");
        db1.execSQL("INSERT INTO emp VALUES ('LAXMI GOYAL (MEDICAL)','9415342377');");
        db1.execSQL("INSERT INTO emp VALUES ('LEKH RAJ SINGH (ELECT MAINT)','9650999127');");
        db1.execSQL("INSERT INTO emp VALUES ('MADAN GOPAL (FUEL HAND.- OPN)','9650994155');");
        db1.execSQL("INSERT INTO emp VALUES ('MADAN MOHAN (OPERATION)','9650999122');");
        db1.execSQL("INSERT INTO emp VALUES ('MADHU BALA (MEDICAL)','9650999236');");
        db1.execSQL("INSERT INTO emp VALUES ('MAHENDER SINGH RAWAT (FUEL HAND.- OPN)','9650999185');");
        db1.execSQL("INSERT INTO emp VALUES ('MAHENDRA KUMAR CHOPRA (ELECT MAINT)','9650993977');");
        db1.execSQL("INSERT INTO emp VALUES ('MAHENDRA SINGH (CHEMISTRY)','9650993876');");
        db1.execSQL("INSERT INTO emp VALUES ('MAHESH KUAMAR MADAN (MECH MAINT)','9650993852');");
        db1.execSQL("INSERT INTO emp VALUES ('MAN SINGH DHARIWAL (MAINT.PLNG.)','9650993814');");
        db1.execSQL("INSERT INTO emp VALUES ('MANASI SHUKLA','9650994875');");
        db1.execSQL("INSERT INTO emp VALUES ('MANDEEP LOOMBA (HR)','9473199543');");
        db1.execSQL("INSERT INTO emp VALUES ('MANISH. (CHEMISTRY)','9650993774');");
        db1.execSQL("INSERT INTO emp VALUES ('MANISHA JAIN (FINANCE)','9650993815');");
        db1.execSQL("INSERT INTO emp VALUES ('MANISHA JAIN','9650999780');");
        db1.execSQL("INSERT INTO emp VALUES ('MANISHA PANDEY (O&G)','9650993607');");
        db1.execSQL("INSERT INTO emp VALUES ('MANJIT SINGH (OPERATION)','9650999275');");
        db1.execSQL("INSERT INTO emp VALUES ('MANJU SHARMA  (MEDICAL)','9650993624');");
        db1.execSQL("INSERT INTO emp VALUES ('MANMOHAN SINGH (HR-EDC)','9650993511');");
        db1.execSQL("INSERT INTO emp VALUES ('MANOHAR LAL (OPERATION)','9650999202');");
        db1.execSQL("INSERT INTO emp VALUES ('MANOJ KUMAR (C&M-STORES)','9650999734');");
        db1.execSQL("INSERT INTO emp VALUES ('MD AZAZ ALAM (OPERATION)','9650999184');");
        db1.execSQL("INSERT INTO emp VALUES ('MEENAKSHI DAS (P & S)','9650993819');");
        db1.execSQL("INSERT INTO emp VALUES ('MERAJ SULTANA (MECH MAINT- OFF SITE)','9650999887');");
        db1.execSQL("INSERT INTO emp VALUES ('MOHD ANWAR ANSARI (C&M-PURCHASE)','9650990635');");
        db1.execSQL("INSERT INTO emp VALUES ('MOHD SULTAN KHAN (MECH MAINT-BOILER)','9650999149');");
        db1.execSQL("INSERT INTO emp VALUES ('MOHEMAD BILAL (ELECT MAINT)','7042497249');");
        db1.execSQL("INSERT INTO emp VALUES ('MOHINDER KUMAR (MAINT.PLNG.)','9650993812');");
        db1.execSQL("INSERT INTO emp VALUES ('Mohinder Singh (ASH MANAGEMENT)','');");
        db1.execSQL("INSERT INTO emp VALUES ('MOHIT GULATI (OPERATION)','9650994093');");
        db1.execSQL("INSERT INTO emp VALUES ('MUKESH KUMAR MEENA (OPERATION)','9650999044');");
        db1.execSQL("INSERT INTO emp VALUES ('Mukesh Kumar Saini (FUEL HAND.- OPN)','9650994186');");
        db1.execSQL("INSERT INTO emp VALUES ('Mulakh Raj (FUEL HAND.- OPN)','9650993892');");
        db1.execSQL("INSERT INTO emp VALUES ('Munshi Prasad (FUEL HAND.- OPN)','7042497264');");
        db1.execSQL("INSERT INTO emp VALUES ('Nanak Chand (OPERATION)','');");
        db1.execSQL("INSERT INTO emp VALUES ('Nand Kishore (FUEL HAND.- OPN)','9650993356');");
        db1.execSQL("INSERT INTO emp VALUES ('Narender Kumar (OPN (MAIN PLANT))','9650993685');");
        db1.execSQL("INSERT INTO emp VALUES ('Narender Singh (OPERATION)','9650994060');");
        db1.execSQL("INSERT INTO emp VALUES ('Naresh Kumar (C & I MAINT)','9650993826');");
        db1.execSQL("INSERT INTO emp VALUES ('NARESH KUMAR KANDPAL (OPERATION)','9650995113');");
        db1.execSQL("INSERT INTO emp VALUES ('Navin Kumar (LAW)','9650998805');");
        db1.execSQL("INSERT INTO emp VALUES ('NAVNEET KUMAR GOLDEN (OPERATION)','9650995595');");
        db1.execSQL("INSERT INTO emp VALUES ('Neeti Sarpal (CHEMISTRY)','9650993756');");
        db1.execSQL("INSERT INTO emp VALUES ('Neetu Chauhan (FINANCE)','9650999347');");
        db1.execSQL("INSERT INTO emp VALUES ('Nihal Chand (FUEL MANAGMENT)','9416212452');");
        db1.execSQL("INSERT INTO emp VALUES ('Nirmal Kumar Sharma (C & I MAINT)','9650996807');");
        db1.execSQL("INSERT INTO emp VALUES ('NISHANT MALHOTRA (OPERATION)','9650994425');");
        db1.execSQL("INSERT INTO emp VALUES ('NITIKA . (FINANCE)','');");
        db1.execSQL("INSERT INTO emp VALUES ('PANKAJ PALIWAL (ELECT MAINT)','9650998101');");
        db1.execSQL("INSERT INTO emp VALUES ('Paramjit Singh Narula (OPERATION)','9650994100');");
        db1.execSQL("INSERT INTO emp VALUES ('Partap Singh (FUEL HAND.- OPN)','9650993901');");
        db1.execSQL("INSERT INTO emp VALUES ('Patnaikuni Adinarayana Patnaik (FUEL MANAGMENT)','9650996876');");
        db1.execSQL("INSERT INTO emp VALUES ('Pawan Kumar Khanna (MAINT.PLNG.)','9650994240');");
        db1.execSQL("INSERT INTO emp VALUES ('Pawan Kumar Sharma (OPERATION)','9650994079');");
        db1.execSQL("INSERT INTO emp VALUES ('PRABHAT GUPTA (OPERATION)','9650993743');");
        db1.execSQL("INSERT INTO emp VALUES ('Prabhat Singh (OPERATION)','9650993702');");
        db1.execSQL("INSERT INTO emp VALUES ('Pradeep Garg (C&M-STORES)','9650994014');");
        db1.execSQL("INSERT INTO emp VALUES ('Pradeep Kumar Sharma (FLD. ENGG.)','9650994940');");
        db1.execSQL("INSERT INTO emp VALUES ('Prasant Kumar Samal (HR-ER)','9650999208');");
        db1.execSQL("INSERT INTO emp VALUES ('Prasanta Kumar Banerjee (O & M)','9650999254');");
        db1.execSQL("INSERT INTO emp VALUES ('Prashant Kumar Singh (CHEMISTRY)','9650993777');");
        db1.execSQL("INSERT INTO emp VALUES ('Praveen Kumar Singh (OPERATION)','9650999607');");
        db1.execSQL("INSERT INTO emp VALUES ('Prem Pal Singh (C & I MAINT- BOILER)','9650993959');");
        db1.execSQL("INSERT INTO emp VALUES ('Priti Chaturvedi (MEDICAL)','9650993609');");
        db1.execSQL("INSERT INTO emp VALUES ('PROLAY CHOWDHURY (VIGILANCE)','9650433329');");
        db1.execSQL("INSERT INTO emp VALUES ('Purushottam Lal Tyagi (FUEL HAND.- OPN)','9650999088');");
        db1.execSQL("INSERT INTO emp VALUES ('Pushpa Rawat (HR-ER)','9650993528');");
        db1.execSQL("INSERT INTO emp VALUES ('R.K. Sood (OPERATION)','9650994111');");
        db1.execSQL("INSERT INTO emp VALUES ('Radhey Shyam (FUEL HAND.- MECH MAINT)','');");
        db1.execSQL("INSERT INTO emp VALUES ('Radhey Shyam (ELECT MAINT)','7042497266');");
        db1.execSQL("INSERT INTO emp VALUES ('RAHUL . (MECH MAINT- BOILER)','9650999445');");
        db1.execSQL("INSERT INTO emp VALUES ('Raj Kumar (OPERATION)','9650993712');");
        db1.execSQL("INSERT INTO emp VALUES ('Raj Kumar Bajaj (OPERATION)','9650993692');");
        db1.execSQL("INSERT INTO emp VALUES ('RAJ NIWAS VERMA (OPERATION)','9650996805');");
        db1.execSQL("INSERT INTO emp VALUES ('Raj Singh Rapraya (OPERATION)','9650999006');");
        db1.execSQL("INSERT INTO emp VALUES ('Raj Vir Singh (OPERATION)','9650995018');");
        db1.execSQL("INSERT INTO emp VALUES ('RAJARSHI . (ELECT MAINT)','9650993744');");
        db1.execSQL("INSERT INTO emp VALUES ('Rajender . (FUEL HAND.- MECH MAINT)','9650997269');");
        db1.execSQL("INSERT INTO emp VALUES ('Rajender Kumar Khatri (OPERATION)','9650994099');");
        db1.execSQL("INSERT INTO emp VALUES ('Rajendra Prasad (CHEM- CENTRAL LAB)','9650996806');");
        db1.execSQL("INSERT INTO emp VALUES ('Rajendra Prasad Yadav (MECH MAINT- OFF SITE)','9650996803');");
        db1.execSQL("INSERT INTO emp VALUES ('Rajendra, Mohan Kulshreshtha (ASH MANAGEMENT)','9650999453');");
        db1.execSQL("INSERT INTO emp VALUES ('Rajesh Bhatia (MAINT.PLNG.)','9650993811');");
        db1.execSQL("INSERT INTO emp VALUES ('RAJESH KUMAR (ENVT. MGT.)','');");
        db1.execSQL("INSERT INTO emp VALUES ('Rajesh Kumar Bhardwaj (LAW)','9650998797');");
        db1.execSQL("INSERT INTO emp VALUES ('Rajinder . (FUEL HAND.- MECH MAINT)','8800388486');");
        db1.execSQL("INSERT INTO emp VALUES ('Rajiv Jain (MAINT.PLNG.)','9650994149');");
        db1.execSQL("INSERT INTO emp VALUES ('Rakesh Kumar (OPERATION)','9650999181');");
        db1.execSQL("INSERT INTO emp VALUES ('RAKESH KUMAR JHA (OPERATION)','9650994071');");
        db1.execSQL("INSERT INTO emp VALUES ('Rakesh Kumar Rai (C&M-STORES)','9650998686');");
        db1.execSQL("INSERT INTO emp VALUES ('Rakesh Kumar Sharma (ORTHOPEDICS)','9650993605');");
        db1.execSQL("INSERT INTO emp VALUES ('Ram Avtar (FUEL HAND.- OPN)','9650999684');");
        db1.execSQL("INSERT INTO emp VALUES ('Ram Briksh (OPERATION)','9650996848');");
        db1.execSQL("INSERT INTO emp VALUES ('Ram Chander Yadav (FUEL HAND.- MECH MAINT)','7042497292');");
        db1.execSQL("INSERT INTO emp VALUES ('Ram Jatan (MAINT.PLNG.)','9650999742');");
        db1.execSQL("INSERT INTO emp VALUES ('Ram Kishan Giri (CHEM- WTP)','9650994245');");
        db1.execSQL("INSERT INTO emp VALUES ('Ram Naresh (FUEL HAND.- OPN)','9871584170');");
        db1.execSQL("INSERT INTO emp VALUES ('Ram Nath (FUEL HAND.- OPN)','7042497270');");
        db1.execSQL("INSERT INTO emp VALUES ('Ram Niwas (OPERATION)','9650994117');");
        db1.execSQL("INSERT INTO emp VALUES ('Ram Sajiwan Yadav (FUEL HAND.- MECH MAINT)','9650999267');");
        db1.execSQL("INSERT INTO emp VALUES ('Ram Sewak Pal (O & M)','9650993660');");
        db1.execSQL("INSERT INTO emp VALUES ('Rama Devi (MEDICAL)','7042497204');");
        db1.execSQL("INSERT INTO emp VALUES ('RAMJI AWASTHI (PLANT CIVIL MAINT.)','9650999738');");
        db1.execSQL("INSERT INTO emp VALUES ('Rampal Singh (MECH MAINT- BOILER)','');");
        db1.execSQL("INSERT INTO emp VALUES ('RAVI RITURAJ . (OPERATION)','9650999177');");
        db1.execSQL("INSERT INTO emp VALUES ('Ravinder Nath Ram (OPERATION)','9650999604');");
        db1.execSQL("INSERT INTO emp VALUES ('Ravinder Singh (C&M-CONTRACTS)','9650998687');");
        db1.execSQL("INSERT INTO emp VALUES ('Ravindra Kumar (FINANCE)','9650999948');");
        db1.execSQL("INSERT INTO emp VALUES ('Reena Srivastava (PATHOLOGIST)','9650993644');");
        db1.execSQL("INSERT INTO emp VALUES ('Rohit  Kumar Mishra (OPERATION)','9650994332');");
        db1.execSQL("INSERT INTO emp VALUES ('Rohit Kumar (HR)','');");
        db1.execSQL("INSERT INTO emp VALUES ('Rohitash Sharma (FUEL HAND.- OPN)','');");
        db1.execSQL("INSERT INTO emp VALUES ('Rohtash Deshwal (MEDICAL)','9650993615');");
        db1.execSQL("INSERT INTO emp VALUES ('Roop Singh (OPERATION)','9650993652');");
        db1.execSQL("INSERT INTO emp VALUES ('Ruma De Sharma (HR-ER)','9650999329');");
        db1.execSQL("INSERT INTO emp VALUES ('S Sreedevi . (HR-EB)','9650993512');");
        db1.execSQL("INSERT INTO emp VALUES ('S.C. Saxena (FUEL HAND.- OPN)','9650999093');");
        db1.execSQL("INSERT INTO emp VALUES ('S.K. Gangal (HR-HINDI)','9650997070');");
        db1.execSQL("INSERT INTO emp VALUES ('S.K. Verma (HR-EDC)','9650993542');");
        db1.execSQL("INSERT INTO emp VALUES ('SACHIN KUMAR (MECH MAINT- TURBINE)','9650996854');");
        db1.execSQL("INSERT INTO emp VALUES ('Sachin Kumar Gautam (OPERATION)','9650999274');");
        db1.execSQL("INSERT INTO emp VALUES ('SAGAR DHINGRA (OPERATION)','9650993745');");
        db1.execSQL("INSERT INTO emp VALUES ('SAGAR LUTHRA (OPERATION)','9650999889');");
        db1.execSQL("INSERT INTO emp VALUES ('SAGIR AHMAD (CHEM-WTP)','9650999289');");
        db1.execSQL("INSERT INTO emp VALUES ('SANDEEP KUMAR (MECH MAINT-BOILER)','9650999289');");
        db1.execSQL("INSERT INTO emp VALUES ('SANJAY JAIN (ELECT MAINT)','9650995438');");
        db1.execSQL("INSERT INTO emp VALUES ('SANJAY KUMAR (VIGILANCE)','9650993922');");
        db1.execSQL("INSERT INTO emp VALUES ('SANTANU DAS (OPERATION)','9650993922');");
        db1.execSQL("INSERT INTO emp VALUES ('SANTOSH KUMAR GARG(FINANCE)','9650993586');");
        db1.execSQL("INSERT INTO emp VALUES ('SANTOSH KUMAR SATSANGI (OPERATION)','9650993738');");
        db1.execSQL("INSERT INTO emp VALUES ('SAPNA BAHRI SURI (FINANCE)','9650999746');");
        db1.execSQL("INSERT INTO emp VALUES ('SAROJ BALA (HR)','9650993544');");
        db1.execSQL("INSERT INTO emp VALUES ('SATBIR SINGH(HR-ES)','9650993544');");
        db1.execSQL("INSERT INTO emp VALUES ('SATBIR SINGH AHLUWALIA (OPERATION)','9650993730');");
        db1.execSQL("INSERT INTO emp VALUES ('SATPAL SINGH(SAFETY)','9650994115');");
        db1.execSQL("INSERT INTO emp VALUES ('SATTAR KHAN (FUEL HAND-OPN)','7042497274');");
        db1.execSQL("INSERT INTO emp VALUES ('SATYA NARAIN YADAV (FUEL HAND-MECH MAINT)','9650998541');");
        db1.execSQL("INSERT INTO emp VALUES ('SATYA PAL SINGH(OPERATION)','9650994157');");
        db1.execSQL("INSERT INTO emp VALUES ('SATYAWAN SHARMA (FUEL HAND-OPN)','9650994268');");
        db1.execSQL("INSERT INTO emp VALUES ('SATYENDRA SAW (OPERATION)','9650998839');");
        db1.execSQL("INSERT INTO emp VALUES ('SATYENDRA KUMAR SINGH(MECH MAINT TURBINE)','9650998839');");
        db1.execSQL("INSERT INTO emp VALUES ('SAURABH GARG (ELEC MAINT)','9650994072');");
        db1.execSQL("INSERT INTO emp VALUES ('SHAKIL HAYAT SIDDIQUE (OPERATION)','9650998839');");
        db1.execSQL("INSERT INTO emp VALUES ('SHANTI SWAROOP (HR-EB)','9650994635');");
        db1.execSQL("INSERT INTO emp VALUES ('SHARMISTA GOHAIN (MECH MAINT-TURBINE)','965099118');");
        db1.execSQL("INSERT INTO emp VALUES ('SHEEL BADAR PARMAR (C N I MAINT)','965099309');");
        db1.execSQL("INSERT INTO emp VALUES ('SHIRISH KUMAR PANDEY (FINANCE)','9650994635');");
        db1.execSQL("INSERT INTO emp VALUES ('SHISH PAL. (OPERATION)','9650993663');");
        db1.execSQL("INSERT INTO emp VALUES ('SHISH PAL SINGH (FUEL HAND-MECH MAINT)','9650993663');");
        db1.execSQL("INSERT INTO emp VALUES ('SHIV OM (ENVT.MGT.)','9650993663');");
        db1.execSQL("INSERT INTO emp VALUES ('SHOBHA RAM(ELECT MAINT)','9650993663');");
        db1.execSQL("INSERT INTO emp VALUES ('SHIRI KANT RAI (FQA(MECH))','9650996875');");
        db1.execSQL("INSERT INTO emp VALUES ('SHWETA AGGARWAL (ELECT MAINT)','965099886');");
        db1.execSQL("INSERT INTO emp VALUES ('SHYAM LAL (FUEL HAND-OPN)','9650994179');");
        db1.execSQL("INSERT INTO emp VALUES ('SITA RAM YADAV (OPERATION)','7042497277');");
        db1.execSQL("INSERT INTO emp VALUES ('SMT.MITLESH GAUTAM (CHEMISTERY)','9650993764');");
        db1.execSQL("INSERT INTO emp VALUES ('SOBAN SINGH(HOSP ADMIN)','7042497215');");
        db1.execSQL("INSERT INTO emp VALUES ('SONIA SINGH (C N I MAINT-TURBINE)','9650994232');");
        db1.execSQL("INSERT INTO emp VALUES ('SOUMEN CHOUDHURY (FUEL HAND-OPN)','9650993764');");
        db1.execSQL("INSERT INTO emp VALUES ('SUBAS CHANDRA MAHATO (CHEMISTERY)','9650993764');");
        db1.execSQL("INSERT INTO emp VALUES ('SUBASH CHANDER CHAUHAN (FLD.ENGG.)','9650993787');");
        db1.execSQL("INSERT INTO emp VALUES ('SUBASH GARG (FUEL HAND.)','965099164');");
        db1.execSQL("INSERT INTO emp VALUES ('SUNIL KUMAR (CHEMISTERY)','9650998282');");
        db1.execSQL("INSERT INTO emp VALUES ('SUNIL KUMAR (CHEM-EXPRESS LAB)','965099011');");
        db1.execSQL("INSERT INTO emp VALUES ('SUNIL KUMAR JAIN (MECH MAINT-OFFSITE)','9650994206');");
        db1.execSQL("INSERT INTO emp VALUES ('SUNITA DAS (MEDICAL)','9650993621');");
        db1.execSQL("INSERT INTO emp VALUES ('SUNNY THAKUR (MECH MAINT-OFFSITE)','7042133963');");
        db1.execSQL("INSERT INTO emp VALUES ('SURAJIT GHOSHC n I MAINT (OPERATION)','9868390312');");
        db1.execSQL("INSERT INTO emp VALUES ('SURENDER SINGH (OPERATION)','9650994125');");
        db1.execSQL("INSERT INTO emp VALUES ('SURENDRA KUMAR SINGH (FUEL HAND-OPN)','9650994257');");
        db1.execSQL("INSERT INTO emp VALUES ('SURESH CHANDER(FUEL HAND-OPN)','9650993918');");
        db1.execSQL("INSERT INTO emp VALUES ('SURESH CHANDRA (IT)','9650993646');");
        db1.execSQL("INSERT INTO emp VALUES ('SURESH KUMAR TANWAR(FINANCE)','9650994894');");
        db1.execSQL("INSERT INTO emp VALUES ('SURINDER KUMAR KAPOOR (FUEL HAND.)','9650997868');");
        db1.execSQL("INSERT INTO emp VALUES ('SUSHIL KUMAR (MECH MAINT-BOILER)','9650993646');");
        db1.execSQL("INSERT INTO emp VALUES ('SUSHIL KUMAR. (FUEL HAND-OPN)','9650993784');");
        db1.execSQL("INSERT INTO emp VALUES ('SUSHIL KUMAR SABHARWAL (OPERATION)','9650994089');");
        db1.execSQL("INSERT INTO emp VALUES ('SUSHMA RANI BHUTANI (FINANCE)','9650993581');");
        db1.execSQL("INSERT INTO emp VALUES ('SWAMI NATH (FUEL HAND-MECH MAINT)','8527335678');");
        db1.execSQL("INSERT INTO emp VALUES ('SWAPAN KUMAR SARKAR (OPERATION)','9650994129');");
        db1.execSQL("INSERT INTO emp VALUES ('T.N RAMESAN (PATHOLOGIST)','9650993645');");
        db1.execSQL("INSERT INTO emp VALUES ('TAJINDER SEHGAL (MEDICAL)','9650995287');");
        db1.execSQL("INSERT INTO emp VALUES ('TARA CHAND (FUEL HAND-MECH MAINT)','9650993335');");
        db1.execSQL("INSERT INTO emp VALUES ('TARUN KUMAR KALRA (PLANT CIVIL MAINT.)','9650993645');");
        db1.execSQL("INSERT INTO emp VALUES ('TEJPAL SINGH (PLANT CIVIL MAINT.)','9650994269');");
        db1.execSQL("INSERT INTO emp VALUES ('TRILOK CHAND (C n I MAINT)','9650994458');");
        db1.execSQL("INSERT INTO emp VALUES ('UPKAR SINGH (CHEM-WTP)','9650994281');");
        db1.execSQL("INSERT INTO emp VALUES ('V.C KAMALAYATHATCHI (C n M)','9650994281');");
        db1.execSQL("INSERT INTO emp VALUES ('VACHASPATI DWIVEDI (MECH MAINT-TURBINE)','9650992482');");
        db1.execSQL("INSERT INTO emp VALUES ('VAIBHAV ANAND JAIN (OPERATION)','9650999829');");
        db1.execSQL("INSERT INTO emp VALUES ('VASUDHA SHARMA (C n M)','9650999277');");
        db1.execSQL("INSERT INTO emp VALUES ('VEENA MEHTA VERMA (HR-ES)','9871087399');");
        db1.execSQL("INSERT INTO emp VALUES ('VIBHUTI NARAYAN SINGH (OPERATION)','965099702');");
        db1.execSQL("INSERT INTO emp VALUES ('VIDYA DHAR SHAH (C n M)','9650998561');");
        db1.execSQL("INSERT INTO emp VALUES ('VIJAY CHAND  (MECH MAINT-BOILER)','9650994146');");
        db1.execSQL("INSERT INTO emp VALUES ('VIJAY JUYAL (PUB.RELN.)','965099130');");
        db1.execSQL("INSERT INTO emp VALUES ('VIJAY KUMAR GOEL (MEDICAL)','9650993616');");
        db1.execSQL("INSERT INTO emp VALUES ('VIJAY KUMAR SHARMA (C n M MAINT)','9650994266');");
        db1.execSQL("INSERT INTO emp VALUES ('VIJAY SHANKAR BHARATI (EEMG)','9650993701');");
        db1.execSQL("INSERT INTO emp VALUES ('VIJAY SINGH MEENA (OPERATION)','965099727');");
        db1.execSQL("INSERT INTO emp VALUES ('VIKAS KUMAR MEENA (MECH MAINT-BOILER)','9650993988');");
        db1.execSQL("INSERT INTO emp VALUES ('VINAY KAPOOR(OPERATION)','965099117');");
        db1.execSQL("INSERT INTO emp VALUES ('VINAY KUMAR MAURYA (MECH MAINT-BOILER)','9650996581');");
        db1.execSQL("INSERT INTO emp VALUES ('VINEET CORNELIUS (IT)','9650993639');");
        db1.execSQL("INSERT INTO emp VALUES ('VINEET KANT RAJORA (FINANCE)','965099187');");
        db1.execSQL("INSERT INTO emp VALUES ('VINOD KUMAR GOEL (C n M MAINT-BOILER)','9650994281');");
        db1.execSQL("INSERT INTO emp VALUES ('VIRENDRA SINGH NEGI (HR-EDC)','9650999314');");
        db1.execSQL("INSERT INTO emp VALUES ('YAIKHOM BASANTA KUMAR (C n M MAINT)','9650994427');");
        db1.execSQL("INSERT INTO emp VALUES ('YOGENDRA KUMAR (OPERATION)','9650994281');");
        db1.execSQL("INSERT INTO emp VALUES ('YOGENDRA SINGH GAUTAM (OPERATION)','9650994078');");
        db1.execSQL("INSERT INTO emp VALUES ('YOGESH VERMA (OPERATION)','9650993726');");
        db1.execSQL("INSERT INTO emp VALUES ('YOGESHWAR KUMAR (ELECT MAINT)','9650994140');");
        db1.execSQL("INSERT INTO emp VALUES ('YUDHISTER KUMAR (OPERATION)','9650994140');");

        Spinner dropdown = (Spinner)findViewById(R.id.spinner);
        String[] items = new String[]{"Select the name:","A C Mohanty (FINANCE)", "A K Tripathi (OPERATION)", "Abha Mathur (O&G)", "ABHAY SINGH (FUEL MANAGMENT)", "ABHIRAM PANDEY AVINASHI (OPERATION)", "ACHINT MITTAL (MECH MAINT- TURBINE)", "AJAY BARELIYA (PLANT CIVIL MAINT.)", "AJEET SINGH VAGLE (OPERATION)", "AKHILESH KUMAR (C&M)", "ALOK RAIZADA (ASH MANAGEMENT)", "AMANPREET KAUR (C&M)", "AMANPREET RATTAN (OPERATION)", "AMIT KAUSHIK (OPERATION)", "AMIT KUMAR GOSWAMI (OPERATION)", "AMIT THAKUR (MAINT. PLNG.)", "ANAND JI AGARWAL (IT)", "ANAND KISHORE MISHRA (FLD. ENGG.)", "ANAND PRAKASH SRIVASTAVA (MEDICAL)", "ANAND PURI (FUEL HAND.)", "ANIL KUMAR (CHEM-EXPRESS LAB)", "ANIL KUMAR GUPTA (FUEL HAND.-OPN)", "ANIL KUMAR KALRA (OPERATION)", "ANIL KUMAR SEHLOTH (MEDICAL)", "ANIL KUMAR SHARMA (FINANCE)", "ANIL KUMAR SINGH (FUEL MANAGMENT)", "ANISH KUMAR (MECH MAINT-OFF SITE)", "ANITA GUPTA (FINANCE)", "ANKUR KUMAR (OPERATION)", "ANSHUL GOEL (OPERATION)", "ANUJA SETH (ELECT MAINT)", "ANURAG TIWARI (MECH MAINT-BOILER)", "ARUN KUMAR MAHAJAN (OPERATION)", "ARUN KUMAR PAL (MAINT. PLNG.)", "ASHISH KUMAR (MECH MAINT. BOILER)", "ASHISH KUMAR AGARWAL (OPERATION)", "ASHISH KUMAR BANSAL (ELECT MAINT.)", "ASHOK KUMAR (EEMG)", "ASHOK KUMAR (FUEL HAND.-OPN)", "ASHOK KUMAR DABAS (ELECT MAINT)", "ASHOK KUMAR KAPOOR (C&I MAINT.)", "ASHOK KUMAR PAL (PLANT CIVIL MAINT. )", "ASHOK KUMAR TRIPATHI (FUEL MANAGMENT)", "ASHOK KUMAR VERMA (OPERATION)", "ASHOK KUMAR VERMA (OPERATION)", "ASIT KUMAR DEY (SAFETY)", "B K BHARALI (MEDICAL)", "B P KALRA (BUSINESS EXCELLENCE)", "BABITA SHEKHAWAT (HR-EDC)", "BABU LAL (FUEL HAND.-OPN)", "BALI RAM (C&M)", "BANWARI LAL (FUEL HAND.-OPN )", "BASANT SINGH (OPN(MAIN PLANT))", "BHAGWAT (MAINT. PLNG.)", "BHARAT LAL SHARMA (FINANCE)", "BHIM SAIN (CHEM-WTP)", "BHUPENDER KUMAR VERMA (FINANCE)", "BHUPINDER SINGH (C&I MAINT)", "BIDESHI (CHEM-EXPRESS LAB)", "BIJALI PRASAD (MECH MAINT-OFF SITE)", "BINOD KUMAR MISHRA (MEDICAL)", "BISHAN SINGH JAGGI (ASH MNGMT.)", "BISHAN SWAROOP (MEDICAL)", "BRAHM PRAKASH (ELECT MAINT.)", "BRAHM SHANKER (MECH MAINT-BOILER)", "BARHM PAL SINGH (OPERATION)", "BRIJ MOHAN SINGH RAWAT (BUSINESS EXCELLENCE)", "BRIKESH KUMAR DUBEY (OPERATION)", "BUDH RAM (FUEL HAND.-OPN)", "CHANDAN CHAKRABORTY (HEAD OF PROJECT)", "CHETAN ANAND SINGH (C&I MAINT.)", "CHETRAM MEENA (OPERATION)", "DALEEP SINGH ARORA (BUSINESS EXCELLENCE)", "DAVID SUNIL MASIH (MEDICAL)", "DEBI PRASAD DUTTA (ELECT MAINT)", "DEEPAK KUMAR DAHIYA (OPERATION)", "DEEPAK KUMAR RAI (MECH MAINT-BOILER)", "DEEPAK SAHAI (MECH MAINT-BOILER)", "DEEPCHAND MEENA (OPERATION)", "DEEPSHIKHA JOSHI (C&I MAINT.)", "DEV RAJ (ELECT MAINT)", "DEVENDER KUMAR (OPERATION)", "DEVINDER KUMAR (P&S)", "DHAN SINGH RAWAT (OPERATION)", "DHARAM VIR YADAV (HR)", "DHARAMVIR SINGH MATHUR (FUEL HAND.-OPN)", "DHARMENDER KUMAR (OPERATION)", "DHIRENDRA KUMAR PATHAK (PAEDIATRICIAN)", "DINA NATH (FUEL HAND.-OPN)", "DINESH CHANDRA SINGH (CHEMISTRY)", "DINESH KUMAR SHARMA (FUEL HAND.-OPN)", "DINESH SINGH (FUEL HAND.-OPN)", "DULI CHAND (OPERATION)", "DUSHYANT KUMAR KAUSHIK (OPERATION)", "ELMA LAL (MEDICAL)", "G MOHAN KUMARAN (OPERATION)", "GAGANDEEP SINGH (FINANCE)", "GANGA RAM YADAV (FUEL MANAGMENT)", "GAURAV AGRAWAL (C & I MAINT.)", "GAURAV GOYAL (MECH MAINT- OFF SITE)","GEETA GAUR (HR-ER)","GEETIKA MOHAN GUPTA (FINANCE)","GHANSHYAM SARAN KHANNA (C&M STORES)",
         "GOPI NATH BHERA (C&M)", "GULBIR SINGH CHAUHAN (OPERATION)", "GURPREET SINGH HEER (MECH MAINT-TURBINE)","GURUCHARAN SINGH (PLANT CIVIL MAINT)","GURUDAS MISHRA (OPERATION)","GYARSI LAL VERMA (OPERATION)", "H.C.AHUJA (C&I MAINT-BOILER)", "HAKIM SINGH RANA (HR-E S)","HARDAN SINGH (FUEL HAND.-OPN)", "HARE RAM (FUEL HAND.-MECH MAIN)", "HARI OM (OPERATION)", "HARI SINGH (OPERATION)", "HARINAM DAS GUPTA (HR-HINDI)", "HARISH CHANDRA BHATT (CHEM-EXPRESS LAB)","HARISH CHANDRA VERMA (MECH MAINT-TURBINE)","HARISH KUMAR BAJAJ (HOP SECT)","HARISH KUMAR SIKRI (CHEMISTRY)","HARJEET KAUR (DENTISTRY)","HARSH GAUR (C&I MAINT)","HARSH KUMAR SRIVASTAVA (MECH MAINT-OFF SITE)","HARSOHENA MULTANI (EEMG)","HARVINDER SINGH (C&M-CONTRACTS)","HAWALDAR RAM (MEDICAL)","HIMAT SINGH (C&I MAINT-TURBINE)","HIRA LAL (OPERATION)","INDER KUMAR GANOTRA (HR)","ISHRAT PARVEEN (MEDICAL)","ISHWER SINGH SAINI (FINANCE)","J.D.NAVEEN KUMAR (FUEL HAND.- OPN)","JAGDISH. (FUEL HAND.- OPN)","JAGDISH KUMAR (FUEL HAND.- OPN)","JAGDISH KUMAR MAHAUR (FUEL HAND.- OPN)","JAI BHAN SINGH (IT)","JAI LAL (FUEL MANAGEMENT)","JAI PRAKASH (FUEL HAND.- OPN)","JASWANT SINGH (FUEL HAND.- OPN)","JAWAHAR SINGH (OPERATION)","JHARKHANDEY SINGH (FUEL HAND.- OPN)","JHINNU PRASAD (FUEL HAND.- OPN)","JODHA SINGH (FUEL HAND.- OPN)","K MANDAL (EEMG)","K.VIJAYA MOHANAN THAMBI (MEDICAL)","KALPANA BASU (IT)","KALYAN MONDAL (C & I MAINT)","KAMALESH PRASAD (MECH MAINT- OFF SITE)","KAMLA PRASAD (ELECT MAINT)","KANCHAN PRIYA (C & I MAINT)","KAPIL. (PLANT CIVIL MAINT)","KAPIL DHVAJ TYAGI (OPERATION)","KARAM VIR SINGH (FUEL HAND.- OPN)","KARAMJIT SINGH (FUEL HAND.- OPN)","KARAN SINGH (FUEL HAND.- OPN)","KARTAVYA AGARWAL (OPERATION)","KAVITA ROHILLA JAIN (HR-EB)","KESARAPU SATYANARAYAN (MAINT.PLNG.)","KESHAV PRASAD MEENA (PLANT CIVIL MAINT.)","KHEVENDER KUMAR (C & I MAINT-BOILER)","KHUB RAM (ELECT MAINT)","KHUSHNANDAN PRASAD SINGH (OPERATION)","KIRAN PATHARIYA (MEDICAL)","KRISHAN CHANDER. (FUEL HAND.- OPN)","KRISHAN CHANDRA SHARMA (OPERATION)","KRISHAN DEV (OPERATION)","KUMAR SAURABH(OPERATION)","KUSH KUMAR SRIVASTWA (OPERATION)","LAKHPAT SINGH (OPERATION)","LALIT SONI (UEL MANAGEMENT)","LAXMI GOYAL (MEDICAL)","LEKH RAJ SINGH (ELECT MAINT)","MADAN GOPAL (FUEL HAND.- OPN)","MADAN MOHAN (OPERATION)","MADHU BALA (MEDICAL)","MAHENDER SINGH RAWAT (FUEL HAND.- OPN)","MAHENDRA KUMAR CHOPRA (ELECT MAINT)","MAHENDRA SINGH (CHEMISTRY)","MAHESH KUAMAR MADAN (MECH MAINT)",". MAMTA RANI","MAN SINGH DHARIWAL (MAINT.PLNG.)","MANDEEP LOOMBA (HR)","MANISH. (CHEMISTRY)","MANISHA JAIN (FINANCE)","MANISHA PANDEY (O&G)","MANJIT SINGH (OPERATION)","MANJU SHARMA  (MEDICAL)","MANMOHAN SINGH (HR-EDC)","MANOHAR LAL (OPERATION)","MANOJ KUMAR (C&M-STORES)","MD AZAZ ALAM (OPERATION)","MEENAKSHI DAS (P & S)","MERAJ SULTANA (MECH MAINT- OFF SITE)","MOHD ANWAR ANSARI (C&M-PURCHASE)","MOHD SULTAN KHAN (MECH MAINT-BOILER)","MOHEMAD BILAL (ELECT MAINT)","MOHINDER KUMAR (MAINT.PLNG.)","Mohinder Singh (ASH MANAGEMENT)","MOHIT GULATI (OPERATION)","MUKESH KUMAR MEENA (OPERATION)","Mukesh Kumar Saini (FUEL HAND.- OPN)","Mulakh Raj (FUEL HAND.- OPN)",". Munna","Munshi Prasad (FUEL HAND.- OPN)","Nanak Chand (OPERATION)", "Nand Kishore (FUEL HAND.- OPN)", "Narender Kumar (OPN (MAIN PLANT))", "Narender Singh (OPERATION)", "Naresh Kumar (C & I MAINT)", "NARESH KUMAR KANDPAL (OPERATION)", "Navin Kumar (LAW)", "NAVNEET KUMAR GOLDEN (OPERATION)", "Neeti Sarpal (CHEMISTRY)","Neetu Chauhan (FINANCE)", "Nihal Chand (FUEL MANAGMENT)", "Nirmal Kumar Sharma (C & I MAINT)", "NISHANT MALHOTRA (OPERATION)", "NITIKA . (FINANCE)", "PANKAJ PALIWAL (ELECT MAINT)", "Paramjit Singh Narula (OPERATION)", "Partap Singh (FUEL HAND.- OPN)", "Patnaikuni Adinarayana Patnaik (FUEL MANAGMENT)", "Pawan Kumar Khanna (MAINT.PLNG.)", "Pawan Kumar Sharma (OPERATION)", "PRABHAT GUPTA (OPERATION)", "Prabhat Singh (OPERATION)", "Pradeep Garg (C&M-STORES)", "Pradeep Kumar Sharma (FLD. ENGG.)", "Prasant Kumar Samal (HR-ER)", "Prasanta Kumar Banerjee (O & M)", "Prashant Kumar Singh (CHEMISTRY)", "Praveen Kumar Singh (OPERATION)", "Prem Pal Singh (C & I MAINT- BOILER)", "Priti Chaturvedi (MEDICAL)", "PROLAY CHOWDHURY (VIGILANCE)", "Purushottam Lal Tyagi (FUEL HAND.- OPN)", "Pushpa Rawat (HR-ER)", "R.K. Sood (OPERATION)", "Radhey Shyam (FUEL HAND.- MECH MAINT)", "Radhey Shyam (ELECT MAINT)", "RAHUL . (MECH MAINT- BOILER)", "Raj Kumar (OPERATION)", "Raj Kumar Bajaj (OPERATION)", "RAJ NIWAS VERMA (OPERATION)", "Raj Singh Rapraya (OPERATION)", "Raj Vir Singh (OPERATION)", "RAJARSHI . (ELECT MAINT)", "Rajender . (FUEL HAND.- MECH MAINT)", "Rajender Kumar Khatri (OPERATION)", "Rajendra Prasad (CHEM- CENTRAL LAB)", "Rajendra Prasad Yadav (MECH MAINT- OFF SITE)", "Rajendra, Mohan Kulshreshtha (ASH MANAGEMENT)", "Rajesh Bhatia (MAINT.PLNG.)", "RAJESH KUMAR (ENVT. MGT.)", "Rajesh Kumar Bhardwaj (LAW)", "Rajinder . (FUEL HAND.- MECH MAINT)", "Rajiv Jain (MAINT.PLNG.)", "Rakesh Kumar (OPERATION)", "RAKESH KUMAR JHA (OPERATION)", "Rakesh Kumar Rai (C&M-STORES)", "Rakesh Kumar Sharma (ORTHOPEDICS)", "Ram Avtar (FUEL HAND.- OPN)", "Ram Briksh (OPERATION)", "Ram Chander Yadav (FUEL HAND.- MECH MAINT)", "Ram Jatan (MAINT.PLNG.)", "Ram Kishan Giri (CHEM- WTP)", "Ram Naresh (FUEL HAND.- OPN)", "Ram Nath (FUEL HAND.- OPN)", "Ram Niwas (OPERATION)", "Ram Sajiwan Yadav (FUEL HAND.- MECH MAINT)", "Ram Sewak Pal (O & M)", "Rama Devi (MEDICAL)", "RAMJI AWASTHI (PLANT CIVIL MAINT.)", "Rampal Singh (MECH MAINT- BOILER)", "RAVI RITURAJ . (OPERATION)", "Ravinder Nath Ram (OPERATION)", "Ravinder Singh (C&M-CONTRACTS)", "Ravindra Kumar (FINANCE)", "Reena Srivastava (PATHOLOGIST)", "Rohit  Kumar Mishra (OPERATION)", "Rohit Kumar (HR)", "Rohitash Sharma (FUEL HAND.- OPN)", "Rohtash Deshwal (MEDICAL)", "Roop Singh (OPERATION)", "Ruma De Sharma (HR-ER)", "S Sreedevi . (HR-EB)", "S.C. Saxena (FUEL HAND.- OPN)", "S.K. Gangal (HR-HINDI)", "S.K. Verma (HR-EDC)", "SACHIN KUMAR (MECH MAINT- TURBINE)", "Sachin Kumar Gautam (OPERATION)", "SAGAR DHINGRA (OPERATION)", "SAGAR LUTHRA (OPERATION)", "SAGIR AHMAD (CHEM-WTP)", "SANDEEP KUMAR (MECH MAINT-BOILER)", "SANJAY JAIN (ELECT MAINT)", "SANJAY KUMAR (VIGILANCE)", "SANTANU DAS (OPERATION)", "SANTOSH KUMAR GARG(FINANCE)", "SANTOSH KUMAR SATSANGI (OPERATION)", "SAPNA BAHRI SURI (FINANCE)", "SAROJ BALA (HR)", "SATBIR SINGH(HR-ES)", "SATBIR SINGH AHLUWALIA (OPERATION)", "SATPAL SINGH(SAFETY)", "SATTAR KHAN (FUEL HAND-OPN)", "SATYA NARAIN YADAV (FUEL HAND-MECH MAINT)", "SATYA PAL SINGH(OPERATION)", "SATYAWAN SHARMA (FUEL HAND-OPN)", "SATYENDRA SAW (OPERATION)", "SATYENDRA KUMAR SINGH(MECH MAINT TURBINE)", "SAURABH GARG (ELEC MAINT)", "SHAKIL HAYAT SIDDIQUE (OPERATION)", "SHANTI SWAROOP (HR-EB)", "SHARMISTA GOHAIN (MECH MAINT-TURBINE)", "SHEEL BADAR PARMAR (C N I MAINT)", "SHIRISH KUMAR PANDEY (FINANCE)", "SHISH PAL. (OPERATION)", "SHISH PAL SINGH (FUEL HAND-MECH MAINT)", "SHIV OM (ENVT.MGT.)", "SHOBHA RAM(ELECT MAINT)", "SHIRI KANT RAI (FQA(MECH))", "SHWETA AGGARWAL (ELECT MAINT)", "SHYAM LAL (FUEL HAND-OPN)", "SITA RAM YADAV (OPERATION)", "SMT.MITLESH GAUTAM (CHEMISTERY)", "SOBAN SINGH(HOSP ADMIN)", "SONIA SINGH (C N I MAINT-TURBINE)", "SOUMEN CHOUDHURY (FUEL HAND-OPN)", "SUBAS CHANDRA MAHATO (CHEMISTERY)", "SUBASH CHANDER CHAUHAN (FLD.ENGG.)", "SUBASH GARG (FUEL HAND.)", "SUNIL KUMAR (CHEMISTERY)", "SUNIL KUMAR (CHEM-EXPRESS LAB)", "SUNIL KUMAR JAIN (MECH MAINT-OFFSITE)", "SUNITA DAS (MEDICAL)", "SUNNY THAKUR (MECH MAINT-OFFSITE)", "SURAJIT GHOSHC n I MAINT (OPERATION)", "SURENDER SINGH (OPERATION)", "SURENDRA KUMAR SINGH (FUEL HAND-OPN)", "SURESH CHANDER(FUEL HAND-OPN)", "SURESH CHANDRA (IT)", "SURESH KUMAR TANWAR(FINANCE)", "SURINDER KUMAR KAPOOR (FUEL HAND.)", "SUSHIL KUMAR (MECH MAINT-BOILER)", "SUSHIL KUMAR. (FUEL HAND-OPN)", "SUSHIL KUMAR SABHARWAL (OPERATION)", "SUSHMA RANI BHUTANI (FINANCE)", "SWAMI NATH (FUEL HAND-MECH MAINT)", "SWAPAN KUMAR SARKAR (OPERATION)", "T.N RAMESAN (PATHOLOGIST)", "TAJINDER SEHGAL (MEDICAL)", "TARA CHAND (FUEL HAND-MECH MAINT)", "TARUN KUMAR KALRA (PLANT CIVIL MAINT.)", "TEJPAL SINGH (PLANT CIVIL MAINT.)", "TRILOK CHAND (C n I MAINT)", "UPKAR SINGH (CHEM-WTP)", "V.C KAMALAYATHATCHI (C n M)", "VACHASPATI DWIVEDI (MECH MAINT-TURBINE)", "VAIBHAV ANAND JAIN (OPERATION)", "VASUDHA SHARMA (C n M)", "VEENA MEHTA VERMA (HR-ES)", "VIBHUTI NARAYAN SINGH (OPERATION)", "VIDYA DHAR SHAH (C n M)", "VIJAY CHAND  (MECH MAINT-BOILER)", "VIJAY JUYAL (PUB.RELN.)", "VIJAY KUMAR GOEL (MEDICAL)", "VIJAY KUMAR SHARMA (C n M MAINT)", "VIJAY SHANKAR BHARATI (EEMG)", "VIJAY SINGH MEENA (OPERATION)", "VIKAS KUMAR MEENA (MECH MAINT-BOILER)", "VINAY KAPOOR(OPERATION)", "VINAY KUMAR MAURYA (MECH MAINT-BOILER)", "VINEET CORNELIUS (IT)", "VINEET KANT RAJORA (FINANCE)", "VINOD KUMAR GOEL (C n M MAINT-BOILER)", "VIRENDRA SINGH NEGI (HR-EDC)", "YAIKHOM BASANTA KUMAR (C n M MAINT)", "YOGENDRA KUMAR (OPERATION)", "YOGENDRA SINGH GAUTAM (OPERATION)", "YOGESH VERMA (OPERATION)", "YOGESHWAR KUMAR (ELECT MAINT)", "YUDHISTER KUMAR (OPERATION)"};
        ArrayAdapter<String> adapter = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_dropdown_item, items);
       // dropdown.setAdapter(adapter);
        //adapter = ArrayAdapter.createFromResource(this, R.array.person_names, android.R.layout.simple_spinner_item);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        dropdown.setAdapter(adapter);
        dropdown.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {

            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
                 text11 = parent.getItemAtPosition(pos).toString();
            }
            @Override
            public void onNothingSelected(AdapterView<?> adapterView) {

            }
            // text11= dropdown.getSelectedItem().toString();
        }); }

    public void onClick(View view) {
        String name = editRollno.getText().toString();
        String phoneno = editName.getText().toString();
        String aadhar = editText.getText().toString();
        String designation = editMarks.getText().toString();
       // String aadhar = editText.getText().toString();
        String concernedperson = text11;
        String date = editText2.getText().toString();
        String time = editText3.getText().toString();

        insertToDatabase(name, phoneno,aadhar, designation, concernedperson, date, time);
        //Cursor c = db1.rawQuery("SELECT * FROM emp WHERE empName='" + editText.getText() + "'", null);
        Cursor c = db1.rawQuery("SELECT * FROM emp WHERE empName='" + text11 + "'", null);
        if (c.moveToFirst()) {
            String number= c.getString(1);
            String message = "There is an appointment of: "+name +" having phone no. is "+ phoneno +" and aadhar card number is "+aadhar +" wants to meet you on "+date +" at "+time;
            SmsManager sms = SmsManager.getDefault();
            sms.sendTextMessage(number, null, message, null, null);
            showMessage("Congratulations!","Your details have been successfully saved.Kindly bring your Aadhar Card at the day of meeting.");
        }
    }

    private void insertToDatabase(String name, String phoneno,String aadhar, String designation, String concernedperson, String date,String time) {
        class SendPostReqAsyncTask extends AsyncTask<String, Void, String> {
            @Override
            protected String doInBackground(String... params) {
                String paramname = params[0];
                String paramphoneno = params[1];
                String paramaadhar = params[2];
                String paramdesignation = params[3];
                String paramconcernedperson = params[4];
                String paramdate = params[5];
                String paramtime = params[6];

                String name = paramname;
                String phoneno = paramphoneno;
                String aadhar = paramaadhar;
                String designation= paramdesignation;
                String concernedperson = paramconcernedperson;
                String date = paramdate;
                String time = paramtime;

                List<NameValuePair> nameValuePairs = new ArrayList<NameValuePair>();
                nameValuePairs.add(new BasicNameValuePair("name", name));
                nameValuePairs.add(new BasicNameValuePair("phoneno", phoneno));
                nameValuePairs.add(new BasicNameValuePair("aadhar", aadhar));
                nameValuePairs.add(new BasicNameValuePair("designation", designation));
                nameValuePairs.add(new BasicNameValuePair("concernedperson", concernedperson));
                nameValuePairs.add(new BasicNameValuePair("date", date));
                nameValuePairs.add(new BasicNameValuePair("time", time));

                try {
                    HttpClient httpClient = new DefaultHttpClient();
                    HttpPost httpPost = new HttpPost(
                            "https://enactive-grids.000webhostapp.com/doc.php");
                    httpPost.setEntity(new UrlEncodedFormEntity(nameValuePairs));

                    HttpResponse response = httpClient.execute(httpPost);

                    HttpEntity entity = response.getEntity();


                } catch (ClientProtocolException e) {

                } catch (IOException e) {

                }
                return "success";
            }

            @Override
            protected void onPostExecute(String result) {
                super.onPostExecute(result);

                Toast.makeText(getApplicationContext(), result, Toast.LENGTH_LONG).show();

            }
        }
        SendPostReqAsyncTask sendPostReqAsyncTask = new SendPostReqAsyncTask();
        sendPostReqAsyncTask.execute(name, phoneno,aadhar, designation,concernedperson, date, time);
    }
    public void showMessage(String title, String message)
    {
        AlertDialog.Builder builder=new AlertDialog.Builder(this);
        builder.setCancelable(true);
        builder.setTitle(title);
        builder.setMessage(message);
        builder.show();
    }


}












